-- US IRS accounting knowledge base seed: Schedule C categories, mileage, meals,
-- home office, sales tax, 1099/EIN, and recordkeeping references. Helps the AI
-- categorize expenses correctly and explain US tax treatment to users.

DELETE FROM public.knowledge_documents
WHERE metadata->>'market' = 'us' AND metadata->>'doc_type' LIKE 'irs_acct_%';

INSERT INTO public.knowledge_documents (title, content, category, source_type, source_url, source_institution, metadata, market) VALUES
('IRS Schedule C — Business Expense Categories', E'## Schedule C (Form 1040) expense lines\n\nUse these lines to categorize deductible business expenses:\n\n- Line 8 Advertising\n- Line 9 Car and truck expenses\n- Line 10 Commissions and fees\n- Line 11 Contract labor (often reported on Form 1099-NEC)\n- Line 13 Depreciation and Section 179\n- Line 15 Insurance (other than health)\n- Line 16 Interest (mortgage and other)\n- Line 17 Legal and professional services\n- Line 18 Office expense\n- Line 20 Rent or lease (vehicles, machinery, other property)\n- Line 21 Repairs and maintenance\n- Line 22 Supplies\n- Line 23 Taxes and licenses\n- Line 24a Travel\n- Line 24b Meals (generally 50% deductible)\n- Line 25 Utilities\n- Line 26 Wages\n- Line 27a Other expenses\n\nKeep receipts and records that show amount, date, vendor, and business purpose.\n\nReference: https://www.irs.gov/forms-pubs/about-schedule-c-form-1040', 'tax', 'guide', 'https://www.irs.gov/forms-pubs/about-schedule-c-form-1040', 'IRS', '{"market":"us","doc_type":"irs_acct_schedule_c"}'::jsonb, 'us'),

('IRS Standard Mileage Rate (business)', E'## Business standard mileage rate\n\nInstead of tracking actual vehicle costs, self-employed taxpayers may deduct a standard rate per business mile driven. The rate is set by the IRS each year and changes annually.\n\n- Record total business miles, dates, and purpose of each trip.\n- Commuting between home and a regular workplace is not deductible.\n- Always confirm the current-year cents-per-mile rate on irs.gov before computing the deduction.\n\nReference: https://www.irs.gov/tax-professionals/standard-mileage-rates', 'tax', 'guide', 'https://www.irs.gov/tax-professionals/standard-mileage-rates', 'IRS', '{"market":"us","doc_type":"irs_acct_mileage"}'::jsonb, 'us'),

('IRS Business Meals — 50% Rule', E'## Deducting business meals\n\nBusiness meals are generally 50% deductible when:\n- The expense is ordinary and necessary for the business.\n- The taxpayer or an employee is present.\n- The meal is not lavish or extravagant.\n\nKeep the receipt and note who attended and the business purpose. Entertainment expenses are generally NOT deductible.\n\nReference: https://www.irs.gov/publications/p463', 'tax', 'guide', 'https://www.irs.gov/publications/p463', 'IRS', '{"market":"us","doc_type":"irs_acct_meals"}'::jsonb, 'us'),

('IRS Home Office Deduction', E'## Home office deduction\n\nA portion of home expenses may be deductible if part of the home is used regularly and exclusively for business.\n\n- Simplified method: a set dollar amount per square foot, up to a maximum area.\n- Regular method: actual expenses allocated by the business-use percentage of the home.\n\nReference: https://www.irs.gov/businesses/small-businesses-self-employed/home-office-deduction', 'tax', 'guide', 'https://www.irs.gov/businesses/small-businesses-self-employed/home-office-deduction', 'IRS', '{"market":"us","doc_type":"irs_acct_home_office"}'::jsonb, 'us'),

('US Sales & Use Tax — Basics', E'## Sales and use tax on purchases\n\nUnlike VAT, the US has no federal sales tax. Sales tax is imposed at the state and local level, so the rate on an invoice depends on the seller/ship-to location. Combined rates commonly range from about 0% (e.g., Oregon, Montana, New Hampshire, Delaware, Alaska state-level) to over 10% in some localities.\n\n- On a receipt, sales tax is shown as a separate line: Subtotal + Sales Tax = Total.\n- Sales tax paid on deductible business purchases is generally part of the cost of the item/expense.\n- Use tax may apply to out-of-state purchases where sales tax was not collected.\n\nReference: https://www.irs.gov/businesses/small-businesses-self-employed/sales-tax', 'tax', 'guide', 'https://www.irs.gov/businesses/small-businesses-self-employed/sales-tax', 'IRS', '{"market":"us","doc_type":"irs_acct_sales_tax"}'::jsonb, 'us'),

('US Vendor Tax IDs — EIN & 1099', E'## EIN and Form 1099-NEC\n\nA US business Employer Identification Number (EIN) has the format XX-XXXXXXX (nine digits). Sole proprietors may instead use an SSN (XXX-XX-XXXX).\n\n- Payments of $600 or more to a non-employee contractor in a year generally require Form 1099-NEC.\n- Collect a Form W-9 from vendors to obtain their legal name and taxpayer ID.\n\nReference: https://www.irs.gov/forms-pubs/about-form-1099-nec', 'tax', 'guide', 'https://www.irs.gov/forms-pubs/about-form-1099-nec', 'IRS', '{"market":"us","doc_type":"irs_acct_ein_1099"}'::jsonb, 'us'),

('IRS Recordkeeping for Receipts & Invoices', E'## What records to keep\n\nFor each business expense keep records showing: amount, date, vendor/payee, payment method, and business purpose. Acceptable records include receipts, invoices, canceled checks, and bank/credit-card statements.\n\n- Keep records generally for at least 3 years from the date the return was filed.\n- Digital copies are acceptable if legible and complete.\n\nReference: https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping', 'tax', 'guide', 'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping', 'IRS', '{"market":"us","doc_type":"irs_acct_recordkeeping"}'::jsonb, 'us');
