-- Coverage: traffic/DMV, jury duty, probate/estate, and student loans.
INSERT INTO public.playbooks
  (doc_type, name, description, trigger_keywords, steps, related_forms, warnings,
   priority, market, jurisdiction, agency)
VALUES
  ('student_loan',
   'Student Loan Notice',
   'A notice about a federal or private student loan — repayment, delinquency, default, or collection.',
   ARRAY['student loan','department of education','federal student aid','nelnet','mohela','aidvantage','sallie mae','navient','loan default','income-driven','idr','repayment'],
   '[{"order":1,"title":"Confirm federal vs private","description":"Federal loans (studentaid.gov) have far more options than private loans. Identify which you have."},
     {"order":2,"title":"Lower your payment","description":"For federal loans, apply for an income-driven repayment (IDR) plan — payments are based on income and can be as low as $0."},
     {"order":3,"title":"If in default, get out","description":"Federal default can be fixed with loan rehabilitation or consolidation, which stops wage garnishment and tax-refund offset."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Federal student-loan default can lead to wage garnishment and seizure of your tax refund — act before that starts.'],
   55, 'us', 'federal', NULL),

  ('traffic_citation',
   'Traffic Ticket / Citation',
   'A traffic citation with options to pay, contest, or take traffic school.',
   ARRAY['citation','traffic ticket','violation','infraction','notice to appear','speeding','moving violation'],
   '[{"order":1,"title":"Find the response deadline","description":"Citations usually require a response within about 15–30 days."},
     {"order":2,"title":"Decide: pay or contest","description":"Paying usually counts as pleading guilty and may add points. Contesting means pleading not guilty and requesting a hearing."},
     {"order":3,"title":"Ask about traffic school","description":"Many courts let you take a defensive-driving course to keep points off your record."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Ignoring a ticket can add penalties and lead to a license suspension or a warrant.'],
   45, 'us', NULL, NULL),

  ('dmv_notice',
   'DMV / License Notice',
   'A DMV notice such as a license suspension, registration issue, or insurance requirement.',
   ARRAY['dmv','dept of motor vehicles','license suspension','suspended','reinstate','registration','sr-22','sr22','driving privilege'],
   '[{"order":1,"title":"Find out why","description":"Read the notice for exactly why the action was taken and what is required to fix it."},
     {"order":2,"title":"Reinstate or request a hearing","description":"Resolve the underlying cause and pay reinstatement fees, or request a DMV hearing by the deadline if you can contest it."},
     {"order":3,"title":"File required insurance","description":"If an SR-22/FR-44 is required, have your auto insurer file it with the state."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Driving on a suspended license can lead to arrest and longer suspensions.'],
   48, 'us', NULL, NULL),

  ('jury_summons',
   'Jury Duty Summons',
   'A summons to serve as a juror, with a date to respond and report.',
   ARRAY['jury','jury duty','summons for jury','juror','report for jury'],
   '[{"order":1,"title":"Respond by the date","description":"Complete and return the questionnaire by the date on the summons — many courts allow online response."},
     {"order":2,"title":"Note your reporting details","description":"Record your reporting date, time, location, and any call-in instructions."},
     {"order":3,"title":"Request excusal if needed","description":"If serving is a hardship, follow the summons instructions to ask to be excused or to postpone."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Ignoring a jury summons can result in fines or being held in contempt.'],
   40, 'us', NULL, NULL),

  ('probate_estate',
   'Probate / Estate Notice',
   'A probate-court or estate notice — for heirs, beneficiaries, creditors, or an executor.',
   ARRAY['probate','estate','executor','personal representative','decedent','letters testamentary','creditor claim','notice to creditors','will'],
   '[{"order":1,"title":"Note the deadlines","description":"Probate has strict deadlines — creditor-claim periods can be just a few months, and will contests have short windows."},
     {"order":2,"title":"Identify your role","description":"Heir/beneficiary, creditor, or executor — your next step depends on which you are."},
     {"order":3,"title":"Consider a probate attorney","description":"Estate rules vary a lot by state; professional advice is worth it when assets or disputes are involved."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Probate deadlines (creditor claims, will contests) are short and strict — missing them can forfeit your rights.'],
   50, 'us', NULL, NULL)
ON CONFLICT (doc_type) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  trigger_keywords = EXCLUDED.trigger_keywords,
  steps = EXCLUDED.steps,
  related_forms = EXCLUDED.related_forms,
  warnings = EXCLUDED.warnings,
  priority = EXCLUDED.priority,
  market = EXCLUDED.market,
  jurisdiction = EXCLUDED.jurisdiction,
  agency = EXCLUDED.agency;
