-- US knowledge base seed (federal, civil, 50 states)
DELETE FROM public.knowledge_documents WHERE metadata->>'market' = 'us' AND (metadata->>'doc_type' IS NOT NULL OR metadata->>'state_code' IS NOT NULL);
INSERT INTO public.knowledge_documents (title, content, category, source_type, source_url, source_institution, metadata, market) VALUES
('SSA Overpayment — What To Do', E'## Overview

Read deadlines carefully. Use official sources only.

Link: https://www.ssa.gov/manage-overpayment', 'tax', 'guide', 'https://www.ssa.gov/manage-overpayment', 'SSA', '{"market":"us","doc_type":"ssa_overpayment"}'::jsonb, 'us'),
('USCIS Request for Evidence (RFE)', E'## Overview

Read deadlines carefully. Use official sources only.

Link: https://www.uscis.gov/forms', 'tax', 'guide', 'https://www.uscis.gov/forms', 'USCIS', '{"market":"us","doc_type":"uscis_rfe"}'::jsonb, 'us'),
('CFPB — Debt collection rights', E'## Overview

Read deadlines carefully. Use official sources only.

Link: https://www.consumerfinance.gov/consumer-tools/debt-collection/', 'tax', 'guide', 'https://www.consumerfinance.gov/consumer-tools/debt-collection/', 'CFPB', '{"market":"us","doc_type":"bank_collection"}'::jsonb, 'us'),
('Court summons — respond in time', E'## Overview

Read deadlines carefully. Use official sources only.

', 'tax', 'guide', NULL, 'Court', '{"market":"us","doc_type":"court_summons"}'::jsonb, 'us'),
('Utility disconnect notice', E'## Overview

Read deadlines carefully. Use official sources only.

Link: https://www.consumer.ftc.gov/articles/utility-shut-offs', 'tax', 'guide', 'https://www.consumer.ftc.gov/articles/utility-shut-offs', 'FTC', '{"market":"us","doc_type":"utility_disconnect"}'::jsonb, 'us'),
('Eviction — tenant rights', E'## Overview

Read deadlines carefully. Use official sources only.

Link: https://www.hud.gov/topics/rental_assistance', 'tax', 'guide', 'https://www.hud.gov/topics/rental_assistance', 'HUD', '{"market":"us","doc_type":"eviction_notice"}'::jsonb, 'us'),
('AK state tax notice — overview', E'## Alaska Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.alaska.gov/', 'tax', 'guide', 'https://tax.alaska.gov/', 'Alaska Department of Revenue', '{"market":"us","state_code":"AK","doc_type":"state_tax_AK_balance_due"}'::jsonb, 'us'),
('AL state tax notice — overview', E'## Alabama Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.revenue.alabama.gov/', 'tax', 'guide', 'https://www.revenue.alabama.gov/', 'Alabama Department of Revenue', '{"market":"us","state_code":"AL","doc_type":"state_tax_AL_balance_due"}'::jsonb, 'us'),
('AR state tax notice — overview', E'## Arkansas Department of Finance and Administration\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.dfa.arkansas.gov/', 'tax', 'guide', 'https://www.dfa.arkansas.gov/', 'Arkansas Department of Finance and Administration', '{"market":"us","state_code":"AR","doc_type":"state_tax_AR_balance_due"}'::jsonb, 'us'),
('AZ state tax notice — overview', E'## Arizona Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://azdor.gov/', 'tax', 'guide', 'https://azdor.gov/', 'Arizona Department of Revenue', '{"market":"us","state_code":"AZ","doc_type":"state_tax_AZ_balance_due"}'::jsonb, 'us'),
('CA state tax notice — overview', E'## Franchise Tax Board\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.ftb.ca.gov/', 'tax', 'guide', 'https://www.ftb.ca.gov/', 'Franchise Tax Board', '{"market":"us","state_code":"CA","doc_type":"state_tax_CA_balance_due"}'::jsonb, 'us'),
('CO state tax notice — overview', E'## Colorado Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.colorado.gov/', 'tax', 'guide', 'https://tax.colorado.gov/', 'Colorado Department of Revenue', '{"market":"us","state_code":"CO","doc_type":"state_tax_CO_balance_due"}'::jsonb, 'us'),
('CT state tax notice — overview', E'## Connecticut Department of Revenue Services\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://portal.ct.gov/drs', 'tax', 'guide', 'https://portal.ct.gov/drs', 'Connecticut Department of Revenue Services', '{"market":"us","state_code":"CT","doc_type":"state_tax_CT_balance_due"}'::jsonb, 'us'),
('DC state tax notice — overview', E'## DC Office of Tax and Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://otr.cfo.dc.gov/', 'tax', 'guide', 'https://otr.cfo.dc.gov/', 'DC Office of Tax and Revenue', '{"market":"us","state_code":"DC","doc_type":"state_tax_DC_balance_due"}'::jsonb, 'us'),
('DE state tax notice — overview', E'## Delaware Division of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://revenue.delaware.gov/', 'tax', 'guide', 'https://revenue.delaware.gov/', 'Delaware Division of Revenue', '{"market":"us","state_code":"DE","doc_type":"state_tax_DE_balance_due"}'::jsonb, 'us'),
('FL state tax notice — overview', E'## Florida Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://floridarevenue.com/', 'tax', 'guide', 'https://floridarevenue.com/', 'Florida Department of Revenue', '{"market":"us","state_code":"FL","doc_type":"state_tax_FL_balance_due"}'::jsonb, 'us'),
('GA state tax notice — overview', E'## Georgia Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://dor.georgia.gov/', 'tax', 'guide', 'https://dor.georgia.gov/', 'Georgia Department of Revenue', '{"market":"us","state_code":"GA","doc_type":"state_tax_GA_balance_due"}'::jsonb, 'us'),
('HI state tax notice — overview', E'## Hawaii Department of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.hawaii.gov/', 'tax', 'guide', 'https://tax.hawaii.gov/', 'Hawaii Department of Taxation', '{"market":"us","state_code":"HI","doc_type":"state_tax_HI_balance_due"}'::jsonb, 'us'),
('IA state tax notice — overview', E'## Iowa Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.iowa.gov/', 'tax', 'guide', 'https://tax.iowa.gov/', 'Iowa Department of Revenue', '{"market":"us","state_code":"IA","doc_type":"state_tax_IA_balance_due"}'::jsonb, 'us'),
('ID state tax notice — overview', E'## Idaho State Tax Commission\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.idaho.gov/', 'tax', 'guide', 'https://tax.idaho.gov/', 'Idaho State Tax Commission', '{"market":"us","state_code":"ID","doc_type":"state_tax_ID_balance_due"}'::jsonb, 'us'),
('IL state tax notice — overview', E'## Illinois Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.illinois.gov/', 'tax', 'guide', 'https://tax.illinois.gov/', 'Illinois Department of Revenue', '{"market":"us","state_code":"IL","doc_type":"state_tax_IL_balance_due"}'::jsonb, 'us'),
('IN state tax notice — overview', E'## Indiana Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.in.gov/dor/', 'tax', 'guide', 'https://www.in.gov/dor/', 'Indiana Department of Revenue', '{"market":"us","state_code":"IN","doc_type":"state_tax_IN_balance_due"}'::jsonb, 'us'),
('KS state tax notice — overview', E'## Kansas Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.ksrevenue.gov/', 'tax', 'guide', 'https://www.ksrevenue.gov/', 'Kansas Department of Revenue', '{"market":"us","state_code":"KS","doc_type":"state_tax_KS_balance_due"}'::jsonb, 'us'),
('KY state tax notice — overview', E'## Kentucky Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://revenue.ky.gov/', 'tax', 'guide', 'https://revenue.ky.gov/', 'Kentucky Department of Revenue', '{"market":"us","state_code":"KY","doc_type":"state_tax_KY_balance_due"}'::jsonb, 'us'),
('LA state tax notice — overview', E'## Louisiana Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://revenue.louisiana.gov/', 'tax', 'guide', 'https://revenue.louisiana.gov/', 'Louisiana Department of Revenue', '{"market":"us","state_code":"LA","doc_type":"state_tax_LA_balance_due"}'::jsonb, 'us'),
('MA state tax notice — overview', E'## Massachusetts Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.mass.gov/dor', 'tax', 'guide', 'https://www.mass.gov/dor', 'Massachusetts Department of Revenue', '{"market":"us","state_code":"MA","doc_type":"state_tax_MA_balance_due"}'::jsonb, 'us'),
('MD state tax notice — overview', E'## Comptroller of Maryland\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.marylandtaxes.gov/', 'tax', 'guide', 'https://www.marylandtaxes.gov/', 'Comptroller of Maryland', '{"market":"us","state_code":"MD","doc_type":"state_tax_MD_balance_due"}'::jsonb, 'us'),
('ME state tax notice — overview', E'## Maine Revenue Services\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.maine.gov/revenue/', 'tax', 'guide', 'https://www.maine.gov/revenue/', 'Maine Revenue Services', '{"market":"us","state_code":"ME","doc_type":"state_tax_ME_balance_due"}'::jsonb, 'us'),
('MI state tax notice — overview', E'## Michigan Department of Treasury\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.michigan.gov/taxes', 'tax', 'guide', 'https://www.michigan.gov/taxes', 'Michigan Department of Treasury', '{"market":"us","state_code":"MI","doc_type":"state_tax_MI_balance_due"}'::jsonb, 'us'),
('MN state tax notice — overview', E'## Minnesota Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.revenue.state.mn.us/', 'tax', 'guide', 'https://www.revenue.state.mn.us/', 'Minnesota Department of Revenue', '{"market":"us","state_code":"MN","doc_type":"state_tax_MN_balance_due"}'::jsonb, 'us'),
('MO state tax notice — overview', E'## Missouri Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://dor.mo.gov/', 'tax', 'guide', 'https://dor.mo.gov/', 'Missouri Department of Revenue', '{"market":"us","state_code":"MO","doc_type":"state_tax_MO_balance_due"}'::jsonb, 'us'),
('MS state tax notice — overview', E'## Mississippi Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.dor.ms.gov/', 'tax', 'guide', 'https://www.dor.ms.gov/', 'Mississippi Department of Revenue', '{"market":"us","state_code":"MS","doc_type":"state_tax_MS_balance_due"}'::jsonb, 'us'),
('MT state tax notice — overview', E'## Montana Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://mtrevenue.gov/', 'tax', 'guide', 'https://mtrevenue.gov/', 'Montana Department of Revenue', '{"market":"us","state_code":"MT","doc_type":"state_tax_MT_balance_due"}'::jsonb, 'us'),
('NC state tax notice — overview', E'## North Carolina Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.ncdor.gov/', 'tax', 'guide', 'https://www.ncdor.gov/', 'North Carolina Department of Revenue', '{"market":"us","state_code":"NC","doc_type":"state_tax_NC_balance_due"}'::jsonb, 'us'),
('ND state tax notice — overview', E'## North Dakota Office of State Tax Commissioner\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.tax.nd.gov/', 'tax', 'guide', 'https://www.tax.nd.gov/', 'North Dakota Office of State Tax Commissioner', '{"market":"us","state_code":"ND","doc_type":"state_tax_ND_balance_due"}'::jsonb, 'us'),
('NE state tax notice — overview', E'## Nebraska Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://revenue.nebraska.gov/', 'tax', 'guide', 'https://revenue.nebraska.gov/', 'Nebraska Department of Revenue', '{"market":"us","state_code":"NE","doc_type":"state_tax_NE_balance_due"}'::jsonb, 'us'),
('NH state tax notice — overview', E'## New Hampshire Department of Revenue Administration\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.revenue.nh.gov/', 'tax', 'guide', 'https://www.revenue.nh.gov/', 'New Hampshire Department of Revenue Administration', '{"market":"us","state_code":"NH","doc_type":"state_tax_NH_balance_due"}'::jsonb, 'us'),
('NJ state tax notice — overview', E'## New Jersey Division of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.nj.gov/treasury/taxation/', 'tax', 'guide', 'https://www.nj.gov/treasury/taxation/', 'New Jersey Division of Taxation', '{"market":"us","state_code":"NJ","doc_type":"state_tax_NJ_balance_due"}'::jsonb, 'us'),
('NM state tax notice — overview', E'## New Mexico Taxation and Revenue Department\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.tax.newmexico.gov/', 'tax', 'guide', 'https://www.tax.newmexico.gov/', 'New Mexico Taxation and Revenue Department', '{"market":"us","state_code":"NM","doc_type":"state_tax_NM_balance_due"}'::jsonb, 'us'),
('NV state tax notice — overview', E'## Nevada Department of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.nv.gov/', 'tax', 'guide', 'https://tax.nv.gov/', 'Nevada Department of Taxation', '{"market":"us","state_code":"NV","doc_type":"state_tax_NV_balance_due"}'::jsonb, 'us'),
('NY state tax notice — overview', E'## New York State Department of Taxation and Finance\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.tax.ny.gov/', 'tax', 'guide', 'https://www.tax.ny.gov/', 'New York State Department of Taxation and Finance', '{"market":"us","state_code":"NY","doc_type":"state_tax_NY_balance_due"}'::jsonb, 'us'),
('OH state tax notice — overview', E'## Ohio Department of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.ohio.gov/', 'tax', 'guide', 'https://tax.ohio.gov/', 'Ohio Department of Taxation', '{"market":"us","state_code":"OH","doc_type":"state_tax_OH_balance_due"}'::jsonb, 'us'),
('OK state tax notice — overview', E'## Oklahoma Tax Commission\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://oklahoma.gov/tax.html', 'tax', 'guide', 'https://oklahoma.gov/tax.html', 'Oklahoma Tax Commission', '{"market":"us","state_code":"OK","doc_type":"state_tax_OK_balance_due"}'::jsonb, 'us'),
('OR state tax notice — overview', E'## Oregon Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.oregon.gov/dor', 'tax', 'guide', 'https://www.oregon.gov/dor', 'Oregon Department of Revenue', '{"market":"us","state_code":"OR","doc_type":"state_tax_OR_balance_due"}'::jsonb, 'us'),
('PA state tax notice — overview', E'## Pennsylvania Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.pa.gov/agencies/revenue', 'tax', 'guide', 'https://www.pa.gov/agencies/revenue', 'Pennsylvania Department of Revenue', '{"market":"us","state_code":"PA","doc_type":"state_tax_PA_balance_due"}'::jsonb, 'us'),
('RI state tax notice — overview', E'## Rhode Island Division of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.ri.gov/', 'tax', 'guide', 'https://tax.ri.gov/', 'Rhode Island Division of Taxation', '{"market":"us","state_code":"RI","doc_type":"state_tax_RI_balance_due"}'::jsonb, 'us'),
('SC state tax notice — overview', E'## South Carolina Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://dor.sc.gov/', 'tax', 'guide', 'https://dor.sc.gov/', 'South Carolina Department of Revenue', '{"market":"us","state_code":"SC","doc_type":"state_tax_SC_balance_due"}'::jsonb, 'us'),
('SD state tax notice — overview', E'## South Dakota Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://dor.sd.gov/', 'tax', 'guide', 'https://dor.sd.gov/', 'South Dakota Department of Revenue', '{"market":"us","state_code":"SD","doc_type":"state_tax_SD_balance_due"}'::jsonb, 'us'),
('TN state tax notice — overview', E'## Tennessee Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.tn.gov/revenue', 'tax', 'guide', 'https://www.tn.gov/revenue', 'Tennessee Department of Revenue', '{"market":"us","state_code":"TN","doc_type":"state_tax_TN_balance_due"}'::jsonb, 'us'),
('TX state tax notice — overview', E'## Texas Comptroller\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://comptroller.texas.gov/taxes/', 'tax', 'guide', 'https://comptroller.texas.gov/taxes/', 'Texas Comptroller', '{"market":"us","state_code":"TX","doc_type":"state_tax_TX_balance_due"}'::jsonb, 'us'),
('UT state tax notice — overview', E'## Utah State Tax Commission\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.utah.gov/', 'tax', 'guide', 'https://tax.utah.gov/', 'Utah State Tax Commission', '{"market":"us","state_code":"UT","doc_type":"state_tax_UT_balance_due"}'::jsonb, 'us'),
('VA state tax notice — overview', E'## Virginia Department of Taxation\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.tax.virginia.gov/', 'tax', 'guide', 'https://www.tax.virginia.gov/', 'Virginia Department of Taxation', '{"market":"us","state_code":"VA","doc_type":"state_tax_VA_balance_due"}'::jsonb, 'us'),
('VT state tax notice — overview', E'## Vermont Department of Taxes\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.vermont.gov/', 'tax', 'guide', 'https://tax.vermont.gov/', 'Vermont Department of Taxes', '{"market":"us","state_code":"VT","doc_type":"state_tax_VT_balance_due"}'::jsonb, 'us'),
('WA state tax notice — overview', E'## Washington Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://dor.wa.gov/', 'tax', 'guide', 'https://dor.wa.gov/', 'Washington Department of Revenue', '{"market":"us","state_code":"WA","doc_type":"state_tax_WA_balance_due"}'::jsonb, 'us'),
('WI state tax notice — overview', E'## Wisconsin Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://www.revenue.wi.gov/', 'tax', 'guide', 'https://www.revenue.wi.gov/', 'Wisconsin Department of Revenue', '{"market":"us","state_code":"WI","doc_type":"state_tax_WI_balance_due"}'::jsonb, 'us'),
('WV state tax notice — overview', E'## West Virginia State Tax Department\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://tax.wv.gov/', 'tax', 'guide', 'https://tax.wv.gov/', 'West Virginia State Tax Department', '{"market":"us","state_code":"WV","doc_type":"state_tax_WV_balance_due"}'::jsonb, 'us'),
('WY state tax notice — overview', E'## Wyoming Department of Revenue\n\n1. Verify notice number, tax year, and amount.\n2. Pay or arrange a plan at the official portal.\n3. Protest/appeal per instructions on the notice.\n\nPortal: https://wyo.gov/revenue', 'tax', 'guide', 'https://wyo.gov/revenue', 'Wyoming Department of Revenue', '{"market":"us","state_code":"WY","doc_type":"state_tax_WY_balance_due"}'::jsonb, 'us');
