-- Auto blog writer: schedule the edge function Mon/Wed/Fri at 07:00 UTC.
-- The function fetches trending agency RSS + Google Trends, generates one
-- SEO blog post per run via OpenAI, and saves it as a draft.

-- Add a flag so the admin can quickly filter auto-generated drafts
-- in the Blog Admin panel.
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT FALSE;

COMMENT ON COLUMN public.blog_posts.auto_generated IS
  'True when the post was generated by the auto-blog-writer edge function.';

-- Schedule: Monday, Wednesday, Friday at 07:00 UTC
-- (Supabase edge-function scheduler via pg_cron + net extension)
SELECT cron.schedule(
  'auto-blog-writer',
  '0 7 * * 1,3,5',
  $$
  SELECT net.http_post(
    url     := current_setting('app.supabase_url') || '/functions/v1/auto-blog-writer',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || current_setting('app.service_role_key')
    ),
    body    := '{}'::jsonb
  );
  $$
);
