-- Comprehensive coverage expansion: dedicated playbooks for the most common
-- actionable US documents that previously fell back to a generic playbook,
-- plus a few additional federal forms. Idempotent (ON CONFLICT upserts).

-- ── Additional forms ──────────────────────────────────────────────────────
INSERT INTO public.forms
  (key, name, description, institution, agency, category, form_type, market,
   pdf_url, fillable_url, online_url, official_source_url)
VALUES
  ('irs_form_8857',
   'Form 8857 — Request for Innocent Spouse Relief',
   'Ask the IRS to relieve you of responsibility for tax, interest, and penalties when your spouse or former spouse improperly reported or omitted items on a joint return.',
   'IRS', 'irs', 'tax', 'form', 'us',
   'https://www.irs.gov/pub/irs-pdf/f8857.pdf', 'https://www.irs.gov/pub/irs-pdf/f8857.pdf',
   NULL, 'https://www.irs.gov/forms-pubs/about-form-8857'),
  ('irs_form_433f',
   'Form 433-F — Collection Information Statement',
   'A shorter financial statement the IRS uses to evaluate installment agreements and currently-not-collectible status for individuals.',
   'IRS', 'irs', 'tax', 'form', 'us',
   'https://www.irs.gov/pub/irs-pdf/f433f.pdf', 'https://www.irs.gov/pub/irs-pdf/f433f.pdf',
   NULL, 'https://www.irs.gov/forms-pubs/about-form-433-f'),
  ('irs_form_12277',
   'Form 12277 — Application for Withdrawal of Filed Notice of Federal Tax Lien',
   'Ask the IRS to withdraw a filed Notice of Federal Tax Lien (for example after you have paid or entered a direct-debit installment agreement).',
   'IRS', 'irs', 'tax', 'form', 'us',
   'https://www.irs.gov/pub/irs-pdf/f12277.pdf', 'https://www.irs.gov/pub/irs-pdf/f12277.pdf',
   NULL, 'https://www.irs.gov/forms-pubs/about-form-12277')
ON CONFLICT (key) DO NOTHING;

-- ── New playbooks ─────────────────────────────────────────────────────────
INSERT INTO public.playbooks
  (doc_type, name, description, trigger_keywords, steps, related_forms, warnings,
   priority, market, jurisdiction, agency)
VALUES
  ('irs_notice_deficiency',
   'IRS Notice of Deficiency (90-day letter)',
   'The IRS proposes additional tax and gives you 90 days to petition the U.S. Tax Court before it assesses the tax.',
   ARRAY['notice of deficiency','90-day','90 day','cp3219a','cp3219n','letter 3219','tax court','statutory notice'],
   '[{"order":1,"title":"Find your 90-day deadline","description":"Your petition to the U.S. Tax Court is due 90 days from the date printed on the notice (150 days if you are outside the U.S.). This deadline is set by law and cannot be extended."},
     {"order":2,"title":"Decide: agree or petition","description":"If you agree, sign the enclosed waiver (Form 5564) and arrange payment. If you disagree, you must petition the U.S. Tax Court to dispute the tax before paying it."},
     {"order":3,"title":"Get professional help","description":"This is a court matter — strongly consider a tax attorney, CPA, or enrolled agent before filing."}]'::jsonb,
   ARRAY['irs_form_9465','irs_form_911'],
   ARRAY['The 90-day Tax Court deadline CANNOT be extended. Missing it means the IRS can assess the tax and you lose the right to challenge it in Tax Court before paying.'],
   90, 'us', 'federal', 'IRS'),

  ('irs_notice_cp2000',
   'IRS CP2000 (Proposed changes / underreported income)',
   'The IRS found income reported by third parties (employers, banks, brokers) that does not match your return and proposes changes. It is not a bill yet.',
   ARRAY['cp2000','underreported','proposed changes','we received information','does not match','underreporter'],
   '[{"order":1,"title":"Compare it to your records","description":"Check the proposed changes against your own 1099s, W-2s, and statements. Sometimes the IRS is right; sometimes it double-counts or misses your cost basis."},
     {"order":2,"title":"Complete the Response form","description":"Mark whether you agree or disagree with each item on the CP2000 Response form included with the notice."},
     {"order":3,"title":"Respond by the deadline","description":"Respond by the date on the notice (usually 30 days). If you disagree, attach copies of documents that support your figures. A CP2000 is NOT an amended return."}]'::jsonb,
   ARRAY['irs_form_9465','irs_form_2848'],
   ARRAY['If you do not respond, the IRS will issue a Notice of Deficiency and assess the additional tax.'],
   80, 'us', 'federal', 'IRS'),

  ('irs_identity_verification',
   'IRS Identity Verification (5071C / 4883C)',
   'The IRS is holding a tax return until you confirm your identity.',
   ARRAY['5071c','4883c','5747c','6330c','verify your identity','identity verification','idverify'],
   '[{"order":1,"title":"Gather what you need","description":"Have the letter, your prior-year return, and the return in question on hand."},
     {"order":2,"title":"Verify online or by phone","description":"Use the official IRS Identity Verification Service at irs.gov, or call the number printed on the letter. Never use a link from a text or email."},
     {"order":3,"title":"If you did not file it","description":"If the IRS is asking about a return you never filed, report identity theft with Form 14039."}]'::jsonb,
   ARRAY['irs_form_14039'],
   ARRAY['Only verify through the official irs.gov site or the phone number on your letter — identity-verification scams are common.'],
   70, 'us', 'federal', 'IRS'),

  ('irs_audit',
   'IRS Audit / Examination',
   'The IRS is examining one or more items on your return and is asking for documentation.',
   ARRAY['examination','audit','letter 566','letter 525','letter 915','cp75','we are examining','your return has been selected'],
   '[{"order":1,"title":"Identify what is questioned","description":"Note exactly which items and tax years the letter is examining, and the response deadline."},
     {"order":2,"title":"Gather supporting records","description":"Collect receipts, statements, and records for those items. Send copies, never originals."},
     {"order":3,"title":"Respond or get representation","description":"Respond by the deadline, or authorize a CPA/attorney/EA with Form 2848 to handle it. You can appeal the result if you disagree."}]'::jsonb,
   ARRAY['irs_form_2848','irs_form_911'],
   ARRAY['Missing the response deadline can lead to the IRS disallowing deductions and assessing more tax.'],
   75, 'us', 'federal', 'IRS'),

  ('irs_penalty',
   'IRS Penalty Notice',
   'The IRS assessed a penalty (such as failure to file, failure to pay, or accuracy). You may be able to get it removed.',
   ARRAY['penalty','failure to file','failure to pay','accuracy-related','we charged you a penalty','abatement'],
   '[{"order":1,"title":"Check First-Time Abatement","description":"If you filed and paid on time for the prior three years, you likely qualify for First-Time Abatement — a clean-history administrative waiver."},
     {"order":2,"title":"Or show reasonable cause","description":"If FTA does not apply, explain the circumstances that prevented compliance (illness, disaster, lost records, reliance on a professional) with dates."},
     {"order":3,"title":"Request removal","description":"Call the number on the notice, send a written request, or file Form 843. Ask for written confirmation."}]'::jsonb,
   ARRAY['irs_form_843'],
   ARRAY[]::TEXT[],
   65, 'us', 'federal', 'IRS'),

  ('irs_lien',
   'IRS Notice of Federal Tax Lien',
   'The IRS filed (or intends to file) a lien securing your tax debt. You have appeal rights and a short deadline.',
   ARRAY['notice of federal tax lien','lien','letter 3172','cdp','collection due process','nftl'],
   '[{"order":1,"title":"Note the 30-day CDP deadline","description":"You generally have 30 days from the lien notice to request a Collection Due Process hearing using Form 12153."},
     {"order":2,"title":"Resolve the balance","description":"Pay in full, set up an installment agreement (Form 9465), or explore an Offer in Compromise (Form 656). A direct-debit installment agreement can support lien withdrawal."},
     {"order":3,"title":"Request withdrawal once eligible","description":"After paying or qualifying, you can ask the IRS to withdraw the lien with Form 12277."}]'::jsonb,
   ARRAY['irs_form_12153','irs_form_9465','irs_form_656','irs_form_12277','irs_form_9423'],
   ARRAY['A filed tax lien can affect your credit and assets. Act before the 30-day Collection Due Process deadline to preserve your appeal rights.'],
   78, 'us', 'federal', 'IRS'),

  ('mortgage_default',
   'Mortgage Default / Foreclosure',
   'Your mortgage servicer says your loan is in default or foreclosure may begin. Free help is available and acting early matters.',
   ARRAY['notice of default','foreclosure','mortgage','loan is in default','acceleration','reinstatement','loss mitigation'],
   '[{"order":1,"title":"Call a HUD-approved housing counselor (free)","description":"Call the HOPE Hotline at 888-995-4673 (888-995-HOPE), available 24/7, or find a local HUD-approved counselor. The service is free."},
     {"order":2,"title":"Apply for loss mitigation","description":"Contact your servicer''s loss-mitigation department and submit a complete application for a loan modification, forbearance, or repayment plan. Keep copies of everything."},
     {"order":3,"title":"Get legal help if sued","description":"If you receive court foreclosure papers, contact local legal aid immediately — deadlines are short and missing them can forfeit your defenses."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Do not ignore the notice. Foreclosure timelines vary by state and can move quickly once started.'],
   72, 'us', 'federal', NULL),

  ('wage_garnishment',
   'Wage or Bank Garnishment',
   'A creditor or court is taking part of your wages or bank funds to satisfy a judgment. Much of your income may be legally protected.',
   ARRAY['garnishment','garnish','writ of garnishment','wage withholding','levy on wages','earnings withholding'],
   '[{"order":1,"title":"Find your exemption deadline","description":"Garnishment papers include a short window to claim exemptions. Note it immediately."},
     {"order":2,"title":"Claim protected income","description":"Social Security, SSI, VA, disability, and a portion of wages are typically protected. File a claim of exemption with the issuing court."},
     {"order":3,"title":"Dispute or get help","description":"If the debt is not yours, dispute it. Garnishment rules are state-specific — legal aid can help you protect more of your income."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['Exemption deadlines are often very short. Acting quickly is the best way to protect your income.'],
   68, 'us', NULL, NULL),

  ('medicaid_notice',
   'Medicaid Notice',
   'A notice about your Medicaid eligibility, renewal, or a denial/termination of coverage.',
   ARRAY['medicaid','fair hearing','redetermination','renewal','eligibility','termination of benefits'],
   '[{"order":1,"title":"Check the deadline","description":"Appeal and renewal deadlines can be very short (sometimes 10–30 days). Find the date on the notice first."},
     {"order":2,"title":"Appeal a denial or termination","description":"If coverage was denied, reduced, or ended, request a fair hearing as the notice instructs. Appealing before the change takes effect may keep your benefits during the appeal."},
     {"order":3,"title":"Complete a renewal","description":"For a renewal or information request, submit the requested documents to your state Medicaid agency by the deadline to avoid losing coverage."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['If you miss the deadline you may lose coverage. Appeal in time to keep benefits during the review where allowed.'],
   60, 'us', 'federal', NULL),

  ('hoa_violation',
   'HOA Violation / Fine',
   'Your homeowners association alleges a covenant violation or has imposed a fine.',
   ARRAY['homeowners association','hoa','covenant','ccr','cc&r','violation','fine','architectural'],
   '[{"order":1,"title":"Request the specifics","description":"Ask the HOA for the exact CC&R provision cited, evidence of the violation, and the hearing/appeal process."},
     {"order":2,"title":"Request a hearing","description":"Most HOAs must offer a hearing before fines become final. Ask that any fines be held until the hearing."},
     {"order":3,"title":"Respond in writing","description":"Send a written response disputing or curing the violation, and keep a copy."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY[]::TEXT[],
   55, 'us', NULL, NULL),

  ('child_support',
   'Child Support Notice',
   'A court or state child-support agency notice about establishing, enforcing, or modifying support.',
   ARRAY['child support','support order','enforcement','arrears','title iv-d','income withholding'],
   '[{"order":1,"title":"Respond by the deadline","description":"If this is a summons or enforcement notice, respond on time — often on an official court form — to protect your rights."},
     {"order":2,"title":"Ask to modify if your situation changed","description":"If your income changed, request a modification through your state child-support agency. Do not simply stop paying."},
     {"order":3,"title":"Arrange a plan for arrears","description":"If you are behind, contact the agency before enforcement (license suspension, garnishment) begins."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY[]::TEXT[],
   55, 'us', NULL, NULL),

  ('court_judgment',
   'Court Judgment',
   'A court has entered a judgment against you. You may have options to respond, appeal, or arrange payment.',
   ARRAY['judgment','default judgment','court judgment','writ','satisfaction of judgment'],
   '[{"order":1,"title":"Read what was decided","description":"Identify the amount, the court, the case number, and any deadline to appeal or move to vacate."},
     {"order":2,"title":"Act on a default judgment quickly","description":"If you were never properly served or missed the hearing, you may be able to ask the court to set aside (vacate) the default — there is usually a short deadline."},
     {"order":3,"title":"Protect your income / arrange payment","description":"A judgment can lead to garnishment. Claim exemptions for protected income and consider a payment arrangement. Free court self-help is available."}]'::jsonb,
   ARRAY[]::TEXT[],
   ARRAY['A judgment can lead to wage or bank garnishment. Deadlines to appeal or vacate are short.'],
   58, 'us', NULL, NULL)
ON CONFLICT (doc_type) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  trigger_keywords = EXCLUDED.trigger_keywords,
  steps = EXCLUDED.steps,
  related_forms = EXCLUDED.related_forms,
  warnings = EXCLUDED.warnings,
  priority = EXCLUDED.priority,
  market = EXCLUDED.market,
  jurisdiction = EXCLUDED.jurisdiction,
  agency = EXCLUDED.agency;
